### ISSUE TITLE
ycashd keeps dropping connections

### ISSUE THREAD

**Issue by justindthomas** [ycashfoundation/yecwallet#14]
Peers keep dropping me. I'm up to 81% with 8 peers, but suddenly my connections will drop to 3 and then to 1 before eventually zeroing out. Restarting ycashd gets it going again for 10 minutes or so.

I thought maybe I needed to allow inbound connections, so I went ahead and set up my port forwarding and firewall rules to allow it, but the behavior doesn't change. Checking netstat, I also don't see any inbound connections, which seems odd.

**Comment by miodragpop** [comment]
Same here, yet I've noticed peers get banned. It's provable by running **./ycash-cli listbanned**
After clearing the list with **./ycash-cli clearbanned**, sync continues, but not for long. Then I have to clear the list again.

**Comment by hloo** [comment]
Can you confirm that you are running ycashd v2.0.5?

There was a problem in ycashd v1.0 that would trigger the behavior that you are describing. Did you ever have ycashd v1.0 on your computer?

**Comment by justindthomas** [comment]
Never installed 1.0 - only 2.0.5 (included in the yecwallet 2.0.5.3 package). I also tried the separate ycashd 2.0.5 download, but the binary is the same.

I did change the ban threshold to 1000 and that's keeping things going longer. I had to step away, so I don't know how much longer yet.

**Comment by miodragpop** [comment]
Built from the latest github src ... Ycash version v2.0.5-2-933370d (2019-07-09 11:28:10 -0700)

**Comment by justindthomas** [comment]
Setting the `banscore` to `1000` helped, but still eventually all nodes stalled out like:

`````
Misbehaving: 34.x.x.x:8833 (900 -> 1000) BAN THRESHOLD EXCEEDED
`````
Doing that did get me up to 94%, so I bumped it to `10000` to hopefully get the chain fully built.

`````
./ycashd --banscore=10000
`````
We'll see how that goes.

**Comment by justindthomas** [comment]
Here are some of the detailed errors that are driving the bans:

`````
2019-07-26 02:04:42 ERROR: ContextualCheckTransaction(): Sapling binding signature invalid
2019-07-26 02:04:42 ERROR: AcceptToMemoryPool: ContextualCheckTransaction failed
2019-07-26 02:04:42 Misbehaving: 114.112.100.194:8833 (700 -> 800)
2019-07-26 02:04:44 ERROR: ContextualCheckTransaction(): Sapling binding signature invalid
2019-07-26 02:04:44 ERROR: AcceptToMemoryPool: ContextualCheckTransaction failed
2019-07-26 02:04:44 Misbehaving: 34.211.223.195:8833 (700 -> 800)
`````

**Comment by hloo** [comment]
@miodragpop and @justindthomas I forgot to ask, what operating system are you using?

**Comment by justindthomas** [comment]
Debian 9 - same base image (in a separate container) I use for zcashd.

**Comment by justindthomas** [comment]
My node did finally complete the initial download with the `banscore` set very high. I'm seeing various connection errors (many due to having no IPv6 stack - I should look in to adding that I guess). But it seems to be staying up to date.

Still no inbound connections though. I'll have to re-check my firewall settings and see if I missed something.

**Comment by hloo** [comment]
As you probably already know, the peer-to-peer port is 8833.

**Comment by justindthomas** [comment]
Yep. Thanks for the reminder.

**Comment by miodragpop** [comment]
Linux Mint 18.3 (Ubuntu 16.04 based) on my home pc and Ubuntu 18.10 on my VPS.

**Comment by hloo** [comment]
[Edit: The solution below has been deprecated. Download v2.0.5.4 instead.]

Try this solution:

# Solution

1. Shutdown YecWallet/ycashd

2. In your ycash.conf file, change the "addnode" statements to "connect". Example:

`addnode=main2.ycash.xyz`

should be changed to:

`connect=main2.ycash.xyz`

Do this for all of your addnode statements. This will insure that you only connect to Ycash cllients, not Zcash clients. You will have fewer connections, but your node will not ban any of them.

3. Restart YecWallet/ycashd.

4. After you sync past block height 570,000, shut down YecWallet/ycashd.

5. In your ycash.conf file, change the "connect" statements back to "addnode" statements.

6. Restart YecWallet/ycashd.

# Working Theory

We have a working theory. To quote the engineer:

"- As the node is syncing, it tries to connect to zcash nodes. This is fine, since Ycash hasn't activated yet, so it can connect to zcash
- The zcash nodes send the user old blocks, this is fine. 
- The zcash nodes also send the user current Txns (from the zcash network, this is the regular network relay). These Txns are invalid, because the sapling binding signature has changed in Ycash (for 2-way replay protection)
- The user's ycash node thinks something suspicious is happening (this is right) and bans the zcash node
- The node is probably still connected to some Ycash nodes, so the sync continues, only slower
- Eventually, all the nodes are zcash nodes, and they all get banned via the the above mechanism, so everything stalls. 

If the user restarts the node, I'm guessing the sync continues, since it will connect to the Ycash seed nodes, but again the same mechanism follows, and all the nodes become zcash nodes, so they get banned, and the sync stalls again."

In your ycash.conf, replace your "addnode" statements with "connect" (so that you only connect to Ycash nodes) until you are synced past block height 570,000. After that, you can switch your ycash.conf back to "addnode".

Novice users should note that YecWallet/ycashd needs to be shutdown before changing the ycash.conf file.

**Comment by miodragpop** [comment]
I've managed to fully sync without stopping the daemon by several manual clearings of the banned peers list. Imho, you should consider total isolation of ycash to zcash network by changing "magic bytes" (pchMessageStart array).

**Comment by justindthomas** [comment]
Out of curiosity, how do the YEC nodes connect to the ZEC nodes when they're running on different ports?

**Comment by hloo** [comment]
When a node identifies itself, it specifies both its ip address and its port number. (Port 8833 is just the default port.) Therefore, ycashd can connect to other nodes running on different ports.

(Befoire the fork, ycashd nodes and zcashd nodes were operating on the same network for a few weeks, communicating with each other.)

@justindthomas, we very much appreciate you sharing that snippet from your log file. It helped us to identify the problem.

**Comment by hloo** [comment]
This problem is fixed by YecWallet v.2.0.5.4 (just released).

**Comment by justindthomas** [comment]
Thanks for the explanation! And I'm happy to help.
